### ISSUE TITLE
cSocketRTScheduler logic error

### ISSUE THREAD

**Issue by avarga** [inet-framework/inet#120]
cSocketRTScheduler causes the deadline of internal simulation events to be missed.

The `cSocketRTScheduler::receiveUntil(const timeval& targetTime)` function is supposed to wait until `targetTime` or until the first packet arrives, whichever is sooner. (`targetTime` is the time at which the next OMNeT++ simulation event is supposed to be executed.) However, internally it relies on repeatedly calling the parameterless `receiveWithTimeout()` function until `targetTime` arrives.  Since `receiveWithTimeout()` doesn't know `targetTime` (it uses a constant timeout, `PCAP_TIMEOUT`), it will miss `targetTime`.

`receiveWithTimeout()` should observe `targetTime`. This will allow a larger `PCAP_TIMEOUT` now that pcap immediate mode is used. `PCAP_TIMEOUT` then will essentially become the user interface refresh interval.

**Comment by rhornig** [comment]
The scheduler now correctly computes the required timeout value. On Linux the UI refresh time was set to 100ms. On other platforms the wait time is still correctly calculated, but the scheduler needs to poll the interface regularly to because of missing APIs that allow waiting without blocking. On non Linux platforms the poll time was set to 500us.
