### ISSUE TITLE
Problem compilation in windows

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#246]
The latest modifications that remove tutorials and showcases and include them like git repositories does not work in windows. The directory structure is used is the structure used in Linux /home/user/.ssh, but windows uses other structure /c/Users/user/.ssh. 

Omnet try to clone the repositories and it fail when try to access to the .ssh directory

**Comment by michaelkirsche** [comment]
This authentication fail is the same under Linux.

The problem seems to be that the submodules were initialized with the URLs pointed to the git@github.com address instead of the publicly available https address. 
Commits d5181cb707bc1c9b0dcf41c092ca842464dd1ce4 and c2d29e5e4c0a9509c5d12aff336fc933399a8c38 added the submodules into the .gitmodules with the git@github address.
This requires a public key to access the repository, which only the INET developers have.

So the URLs in the .gitmodules need to be adjusted to the HTTP(S) addresses:

> [submodule "tutorials"]
	path = tutorials
	url = https://github.com/inet-framework/inet-tutorials.git
[submodule "showcases"]
	path = showcases
	url = https://github.com/inet-framework/inet-showcases.git

For already checked out INET projects, the following solutions are possible in the meantime:

- adjust the code in the .gitmodules file
- edit the local .git/config file and either
  - change the git@github URLs there too or
  - delete the submodules configuration and
  - do the git submodule update --init process again 
  - (or do the git recursive checkout or pull the submodules individually with the changed URLs...)

**Comment by rhornig** [comment]
Hmm, for some reason I have assumed that git@ protocol is more generic, but indeed it is working ONLY if you actually set up an SSH key. I have changed the URLS to HTTPS. Exisiting installation can be changed as @michaelkirsche suggested above. Thanks for reporting this.
