### ISSUE TITLE
Segmentation Fault in RadioMedium (dangling pointer)

### ISSUE THREAD

**Issue by riebl** [inet-framework/inet#250]
Occasional crashes occur in simulations with dynamic hosts, i.e. where radios are added and removed dynamically during simulation.
RadioMedium stores ongoing transmissions (ITransmission) and these have an getter for retrieving the transmitting radio (ITransmission::getTransmitter). However, with increasing number of network nodes the likelihood increases that a network host is removed while one of its transmission is still on its way. In this situation ITransmission::getTransmitter returns a dangling pointer.

A typical stack trace of such an error looks like this:
inet::physicallayer::RadioFrame::getListening() at RadioFrame.cc:60 0x7fffd3fdbb14	
inet::physicallayer::Radio::endReception() at Radio.cc:473 0x7fffd3fd6a72	
inet::physicallayer::Radio::handleReceptionTimer() at Radio.cc:255 0x7fffd3fd3e14

One way to deal with this issue is to check in Radio::{start,continue,end,abort}Reception if the transmitter radio is still registered at the RadioMedium. This solution has been proposed by Nico Brüttner.
What would be the preferred way by INET core developers to solve this problem?

**Comment by levy** [comment]
Thanks for bringing this up, although I'm not sure how to properly fix this issue. If we were only considered with the numerical output of simulations, then I would say:

For a signal which already completely left the transmitter and which just propagates on the medium, I would say that the signal should not be asked to return the transmitter at all. All transmitter data that is relevant for any further processing should have been already copied to the signal.

For other signals which are being transmitted at the moment when the radio is deleted from the simulation, I would say that the signal propagation should be changed to propagate the transmission abort event. And again, all transmitter data that is relevant for further processing should have been already copied to the signal.

So, I guess what I'm saying is that the transmitter should not be checked on the radio medium, because it should not be used at all. At least that's the case for the evolution of the simulation.

On the other hand, for various reasons it might be desirable to keep a reference in the signal to the transmitter. For example, for the sake of logging or debugging, e.g. knowing where the signal originates from.

Currently, the ITransmission::getTransmitter() function's documentation says that it never returns a nullptr. If we allow removing *and* deleting radios at any moment, then it's clearly wrong.

Do you really need to delete those radios as opposed to just removing them from the medium?

**Comment by riebl** [comment]
I would really prefer to delete the radios because it might be hundreds of radios entering and leaving the simulation during one run. Having ITransmission::geTransmitter() for debugging is valuable for sure. Resetting the IRadio pointer manually in each Transmission object seems overly complicated to me and would increase the complexity of the ITransmission interface.

While ITransmission, IArrival, IListenning, IReception (...) are owned by RadioMedium (or its ICommunicationCache), the radios are not. Thus, I propose to treat IRadio* differently:
1) IRadio* shall not be stored by any object except RadioMedium itself. When a IRadio pointer is passed to any object it is allowed to access the radio during the function call.
2) If an object needs to access a radio later on it shall only store the cModule id and try to get the radio instance via getModule(id), which might return nullptr if not existing any longer. This might also get wrapped by a RadioHandle helper class.

Since a RadioFrame does not exceed the lifetime of the owning RadioMedium it might also be safer to replace "transmission->getTransmitter()->getMedium()" by a locally stored pointer to the RadioMedium. Of course, this slightly increases the object size but this is justifiable in my opinion.

I am also willing to help patching this issue as soon as it is clear how this should be done.

**Comment by levy** [comment]
You are right about the proposed solution. 

One problem I see is that aborting a transmission is currently not implemented in INET. If you delete a radio while it's transmitting a signal, then you also have to abort the current transmission. Otherwise the signal could be correctly received by another radio, or it could incorrectly prevent the reception of another signal, etc.

Unfortunately, there are a few problems with aborting a transmission in the current OMNeT++ architecture. The first packet that was sent with the start of the signal already tells the transmission duration. We can send another message to the receivers to abort their reception for the given transmission. The problem is that it will have no effect on the message animation in the graphical user interface, resulting in misleading animation. Also it will have no effect on the eventlog and thus on the presentation of the transmission in the Sequence Chart tool.

Nevertheless, storing the radio module id instead of the radio pointer still allows to delete a radio when it is not transmitting, which is better than what we have now.

**Comment by riebl** [comment]
I for one am not too much worried about minor animation glitches :-)
Please let me know when I can help you writing and/or testing a patch.

**Comment by levy** [comment]
If you could come up with a patch regarding replacing the transmitter and receiver pointers in TransmissionBase and ReceptionBase with module ids that would be nice. At least this would allow to delete a radio when it is not actually transmitting.

When this is done, we can come back to the abort transmission feature. Unfortunately, I'm quite busy with the upcoming INET-3.6 and INET-3.99 (pre 4.0) releases.

**Comment by riebl** [comment]
Fixed by #266
