### ISSUE TITLE
Node Mobility

### ISSUE THREAD

**Issue by ManiAm** [inet-framework/inet#298]
Few suggestions:

1. Shouldn't the LinearNodeDistributionMobility moved into the static folder and not single. It is basically a derived class of the stationaryMobility and all stationary-related mobilities are in static folder.

2. How come setting the mobility constraintArea parameter is not mandatory in 'StationaryMobility' and 'StaticConcentricMobility', but the user should change the default constraintArea (that are infinity) in 'LinearNodeDistributionMobility' and 'StaticGridMobility', otherwise an error is shown? In other words, why INET forces the user to define a constrain area for those two mobilities?

**Comment by levy** [comment]
1. You are right about this. The model should be moved into static and renamed, I really don't know why the word Node is included in its name.

2. For StationaryMobility, the constraintArea is only used for random positioning. For StaticGridMobilitiy, the constraintArea seems to be mandatory, because it needs a rectangular area parameter. The two mentioned mobility models were contributed, and I guess they just happen to be that way.

**Comment by levy** [comment]
I moved and also renamed the mentioned mobility model in the integration branch.

**Comment by ManiAm** [comment]
Thanks! The integration branch does not seem to be compile-able at this moment. Moreover, there are many NED errors too. Merging the fixes-for-integration branch into it solves part of the problem, but I get many conflicts. I guess I need to wait for the next pre-4.0 release.

**Comment by levy** [comment]
The reason for the build error is that you need a not yet released OMNeT++ version for the INET integration branch to compile.
