### ISSUE TITLE
RIP Protocol-specific routing data

### ISSUE THREAD

**Issue by ManiAm** [inet-framework/inet#324]
The AODV and DYMO have their own protocol-specific information that they keep within each routing entry.

![2018-05-02_21-19-19](https://user-images.githubusercontent.com/5473998/39559903-96f0298c-4e4e-11e8-8847-dc9620016c45.png)

Similarly, RIP also keeps track of some protocol-specific information. But I noticed that the RIP module has an internal routing table that is separate from the routing table in the IPv4 module. Is there any reason behind this redundancy?

Routing table of router1 in RIP module:

![2018-05-02_19-56-58](https://user-images.githubusercontent.com/5473998/39559925-bcb6f42a-4e4e-11e8-9e49-5764ddedf8fd.png)

Routing table of router1 in IPv4 module:

![2018-05-02_19-56-35](https://user-images.githubusercontent.com/5473998/39559927-c0309192-4e4e-11e8-83f3-804899e56d08.png)

Shouldn't the protocol-specific data that RIP keeps in a separate module internally, get merged with the real routing table that the router consults for packet forwarding? (very similar to how AODV and DYMO do)

**Comment by levy** [comment]
I don't know too much about RIP, but in general I would say yes, RIP should store its route related protocol specific data the same way AODV and DYMO do. I guess this is the way it is, because it evolved into this way historically. If there's no other reason, then if you send a pull request that is easy to follow, we can merge it into integration.

**Comment by ManiAm** [comment]
ok, I will send a pull request once finished.

**Comment by ManiAm** [comment]
pull request #331
