### ISSUE TITLE
Runtime error during serialization

### ISSUE THREAD

**Issue by ManiAm** [inet-framework/inet#337]
Setting the CRC or FCS mode to 'computed' causes a serialization error

![2018-05-24_14-34-18](https://user-images.githubusercontent.com/5473998/40514998-f9b16528-5f5f-11e8-8ac4-9422247707f6.png)

To reproduce the error you can use the following attached scenario:

[sampleScenario.tar.gz](https://github.com/inet-framework/inet/files/2037181/sampleScenario.tar.gz)

Commenting out these lines in the configuration file suppress the error, but in the PCAP recording scenario, these parameters are mandatory and cannot be commented.

```
**.crcMode = "computed"
**.fcsMode = "computed"
```

**Comment by levy** [comment]
Unfortunately, there's no RIP packet serializer implemented at the moment. Actually, it's only the RIP data part of the packet what is missing, the rest is, of course, available. You can take a look at UdpHeaderSerializer.cc, for example, to see how to implement one if you really need this.

I leave this open, so that we see that it's missing.

**Comment by ManiAm** [comment]
pull request #340
