### ISSUE TITLE
Qtenv window slightly changes under sudo mode

### ISSUE THREAD

**Issue by ManiAm** [inet-framework/inet#338]
I was trying to run the emulation example in OMNET++ and run the IDE in sudo mode. I noticed that the IDE appearance has changed in the sudo mode:

Normal user mode:
![normal_env](https://user-images.githubusercontent.com/5473998/40518110-ba00af52-5f6d-11e8-9c49-3a9f27353432.png)

Sudo mode:
![sudo_env](https://user-images.githubusercontent.com/5473998/40518118-c5549512-5f6d-11e8-83e6-6c8b3d463f07.png)

Some widgets (like the simulation speed slider) are changed and the location of the menu bar has also changed. I am not sure if this is expected or not. Also I am not sure if this is INET-related (its more of a OMNET++-related issue).

Edit: Probably this is due to the environment variables that gets reset in the sudo environment and affects QT library in terms of finding path to widgets, etc.

**Comment by torokati44** [comment]
This has nothing to do with INET, and not very much with OMNeT++ either.
It is simply caused by the fact that Qt stores its settings (like the widget style) separately for each user - and with `sudo`, the settings of the `root` user are applied.

See some examples of the countless similar issues on the internet:
- https://bugreports.qt.io/browse/QTBUG-24045
- https://superuser.com/questions/1263308/how-to-force-qt-application-running-via-sudo-to-use-user-theme-fonts-configurati

I don't think this is particularly important, but thanks anyway for your trouble to report it.

By the way, if this really annoys you, the `QT_STYLE_OVERRIDE` can be set to `fusion` for example, to achieve a consistent, platform- and user-agnostic style.

**Comment by ManiAm** [comment]
Thanks Torok for your time and patience. OMNET++ uses QT extensively and it's hard for me (none-contributor) to figure out if the problem is with OMNET++ or QT.

as a follow up on this issue, the README.md file (in inet/examples/emulation) asks the user to run OMNET++ in privilege mode in order to give sudo access to the libpcap to capture frames. Probably, it's a good idea to add a note in that file to warn the users about running the IDE in sudo mode, cause all write accesses by the IDE would be done in sudo, and once the user changes back to the non-privilege mode again, he/she might end up with these kinds of errors:

![2018-05-25_11-51-59](https://user-images.githubusercontent.com/5473998/40561971-1a75eedc-6014-11e8-994a-f3f80a04b046.png)

As a solution, probably the libpcap code can be run in a separate process and the INET code can interact with it through sockets. In this case, the process alone can be elevated to sudo. Another possible solution is to only give INET the [capability ](https://linux.die.net/man/7/capabilities)that it need for network access.

**Comment by torokati44** [comment]
Even without adding this capability, I'm not sure the IDE has to be started with sudo, only the simulation itself. And if this is true, I'd really advise anyone against starting the whole IDE as root, because firstly, it causes problems like you described, and secondly, it's A LOT of code, from many different sources. Maybe even too much to be trusted this easily. I think.

Adding the capability certainly is an elegant and clean way of handling this, maybe the README should include this too, as a better alternative. What do you think, @levy?

By the way, you could also have set up the launch configuration in the IDE to start the simulator (most likely `opp_run[_dbg]` with INET) through a "graphical sudo" wrapper, like `gksu` (IIRC). I guess that also would have worked, just not this nicely.

**Comment by ManiAm** [comment]
The above solution (setcap) solves the emulation problem in normal run. When running the simulation in debug mode (gdb) the problem still persists, because the opp_run_dbg is not invoked directly anymore. GDB is involved.

![2018-05-25_15-14-10](https://user-images.githubusercontent.com/5473998/40568260-63e41944-602e-11e8-996a-11e076a831f0.png)

**Comment by levy** [comment]
I updated the README files for the emulation examples to include a section which describes your solution as the suggested one. Thank you!
