### ISSUE TITLE
Windows clang toolchain of OMNeT++ 5.4.1 cannot link models against inet v4.0.0

### ISSUE THREAD

**Issue by sommer** [inet-framework/inet#379]
On Windows and when using the **clang** toolchain of OMNeT++ 5.4.1, linking a simulation model against inet v4.0.0 triggers multiple linker errors of the style `undefined reference to typeinfo for`.

Seems like issue #191 has resurfaced with the fix of issue #257.

Switching to the **gcc** toolchain works around the problem (though the minor fix described in issue #378 is still required to get, e.g., [this code](https://github.com/sommer/veins/blob/b6b16fd/subprojects/veins_inet/src/veins_inet/VeinsInetApplicationBase.cc) to work)

**Comment by ohrensessel** [comment]
I came across the same problem with OMNeT++ and INET-4.1.0, however the fix mentioned from #378 doesn't seem to be required any more. For me, switching to gcc solved the problem.

**Comment by sommer** [comment]
Correct. Patch #378 has been merged between INET-4.0.0 and INET-4.1.0. Note, however, that this bug tracks two issues. I believe, we should leave this open as long as linking with INET does not seem to work with the default toolchain of OMNeT++.

**Comment by rhornig** [comment]
Confirmed. Sadly typeinfo is not exported for abstract classes that has no out-of-line function definition because the compiler cannot decide in which compilation unit stick the typinfo. Adding `--export-all-symbols` would force to export everything including the typinfo, but sadly INET is so big that it would result some 80.000 symbols exported, and now the surprise. The ordinal index number in the export table is 16bit!. Yes on 64-bit windows, a DLL cannot export more than 65535 symbols. With all symbols exported, the 16bit ordinals wrap around and various calls from an INET dependent models end up in totally random functions causing crashes and other strange behavior...

So sadly using --export-all-symbols is not an option (unless we split INET into 2 DLLs).

The other way to force the proper export of typeinfo is to create at least an empty destructor definition for **each** abstract class and add `-Werror=waek-vtables`  to forbid any such construct in INET in the future.

**Comment by avarga** [comment]
See bug https://bugs.llvm.org/show_bug.cgi?id=27966

**Comment by rhornig** [comment]
Implemented a workaround that explicitly adds the typeinfo symbols on Windows when clang is used as a compiler: 505af4d10f32d0a3aa505dabbe1ed68bdbb2a6da
