### ISSUE TITLE
Cannot abort PAUSE (LFC) before timeout

### ISSUE THREAD

**Issue by danushkam** [inet-framework/inet#390]
Usually it should be possible to abort link level flow control on an interface (Ethernet flow control) before the original time elapses. This can be fixed with a minor change to PAUSE frame handling logic in both EtherMAC and EtherMACFullDuplex classes. I am happy to submit a patch.

**Comment by avarga** [comment]
We are somewhat ambivalent on the topic of PAUSE frames. It is our impression, based on e.g. https://en.wikipedia.org/wiki/Ethernet_flow_control, that PAUSE frames are an obsolete and rarely used feature of Ethernet that often causes more problems than it solves. We have therefore considered removing PAUSE support from INET Framework altogether, but have been waiting for more input. Therefore, we'd appreciate learning your position on PAUSE frames. Do you think they have their use? What do you need it for? Maybe Cisco's priority flow control extension would be worth implementing instead/additionally?

**Comment by danushkam** [comment]
Yes you are right. My understanding about PAUSE frames is the same as
yours. Anyway Cisco's version (PFC), which came up as a solution to the
issues in PAUSE, is "heavily" used. Basically it uses traffic classes to
selectively pause individual flows as opposed to the whole link as in plain
old PAUSE. Even in my work I am doing PFC atop PAUSE as I just use one
priority class. Specially in datacenter networks PFC is essential to make
the network lossless. This equally applies to RDMA-based networks as well
as the ones that use Datacenter Bridging. Having said that, PFC has it's
own issues like congestion spreading, deadlocks, etc so there are research
efforts looking into making networks lossless without using PFC but I doubt
PFC will die very soon. So it's something definitely worth having in INET.

These are a couple things you may need to think of in terms of implementing
PFC in INET.

1. PFC is triggered based on queue depth on ingress queues. But in INET
there is no notion of ingress queue as far as I know. At least in the
version I use (3.6.4).
2. The current PAUSE implementation in INET assumes the PAUSE frames are
triggered by a layer above LLC but the queue actually sits on the NIC. But
I think communication between layers is supported in the latest version of
INET and this is not a problem anymore?

Thanks,
Danushka

**Comment by avarga** [comment]
Danushka, thanks for the clarification! Knowing what you just wrote about PFC, we definitely want to have it in INET. I looks reasonable that we also keep (and improve) PAUSE frame support, because it's useful for comparison, and also as a good basis for the PFC implementation. So, your patches to improve PAUSE frames would be most welcome.

Going towards PFC, I guess first we'll need support for VLAN tagged frames (802.1Q) so that frames can carry a priority field. Frame representation has been completely changed in INET 4.0 to support emulation and more features, and while Ethernet in INET 4.0 it still does not have 802.1Q headers, we plan to add this feature in the near future (next week?) as it is also needed by multiple other projects. (We don't plan to actively work on 3.x any more, apart from bugfixing, so if you want to stay on top of things, it'll be probably a good idea to switch to 4.x sometime.)

We'll also need to reconsider switch architecture in INET, as in 4.0 there is still no ingress queue, all incoming frames are relayed immediately to output interfaces. I'll discuss this with my colleagues early next week, and will keep you posted.

**Comment by danushkam** [comment]
I tried to switch to 4.0 when it was released but figured out it required quite a bit of rework in my current code base. Yes I will give it a shot when I get a leeway.

I guess the patches should be submitted against the current master? I will submit two patches, one for this and another for #391.

Thanks!

**Comment by danushkam** [comment]
Here's my patch for this issue.

Thanks!

[Patch.390.zip](https://github.com/inet-framework/inet/files/2456162/Patch.390.zip)

**Comment by avarga** [comment]
Thank you for the patch! We merged it in both the 3.x and 4.x (=master) branch.

If you wish, we could have a look at your code to see how difficult it would be to port it to INET 4.0, and help you with it or at least give you some hints. Implementing the 802.1Q tag is currently underway for 4.x.

**Comment by danushkam** [comment]
Thanks for applying the patch.

In terms of porting my code to INET 4.0, let me give it a shot and get back to you if I get stuck. Appreciate your willingness to help.

Thanks!
