### ISSUE TITLE
Usage of SQLite Result Files during a wireless simulation run

### ISSUE THREAD

**Issue by ababila** [inet-framework/inet#417]
I think the problem is globally about using outputvectormanager-class="omnetpp::envir::SqliteOutputVectorManager"
outputscalarmanager-class="omnetpp::envir::SqliteOutputScalarManager"

I got this error "SQLite error 'NOT NULL constraint failed: vectorData.value' on file 'results/PartiallyOverlappingFrequencyBands-#0.vec' " when testing the scenarios of "https://github.com/inet-framework/inet-showcases/tree/wip/wireless/crosstalk". 
(And many other scenarios)

But curiously there is still some data in the files of the "result" folder.

Hence, thanks to this error one cannot use opp_runall tool  to run all repetitions of a simulation and save the results in SQLite format.

**Comment by adamgeorge309** [comment]
There was a problem with the recording of NaN values. You can fix this by editing the `omnetpp/src/common/sqliteresultfileschema.cc` file. Look for this line:
 
"CREATE TABLE IF NOT EXISTS vectorData "
"( "
    "vectorId      INTEGER NOT NULL REFERENCES vector(vectorId) ON DELETE CASCADE, "
    "eventNumber   INTEGER NOT NULL, "
    "simtimeRaw    INTEGER NOT NULL, "
    **"value         NUMERIC NOT NULL "**
"); "

Remove the "NOT NULL" from the `value` variable:

**"value         NUMERIC"**

This will be fixed in OMNeT++. Thanks for reporting this!

**Comment by ababila** [comment]
It works! 
Thank you too.
