### ISSUE TITLE
The process running the simulation model block with Dimentional models when **.dimensions="time frequency"

### ISSUE THREAD

**Issue by ababila** [inet-framework/inet#422]
I am inspired by the unfinished showcase (https://github.com/inet-framework/inet-showcases/tree/wip/wireless/crosstalk) to test and understand the implementation of the radio crosstalk effect simulation in INET.

I think there is a BUG when using dimensional models with **.dimensions="time frequency". The process running the simulation model block until I'm forced to kill it with the command like 'kill -9 PID''.

I am getting to the bug when I tried to simulate the coexistence of 802.11 and 802.15.4 over the 2.4GHz frequency band.

Here are the *.ned and .ini files of my experiment: https://gist.github.com/ababila/10ba38538a6248b2729f877715d57cc1

Globally, in the experiment, I am varying the distance between the 802.11 and 802.15.4 network. (hoping to see for example the  minSNIR of the ratio interfaces increase when the distance between the two network increase).

The error occurs particularly at:  run=2, when $i=225,$0=230 (just mobility data), $repetition=0

    -c = NonOverlappingChannels from the event #11 561 (bug state 1) and,
    -c =  OverlappingChannels from the event #11 585 : (bug state 2).

Furthermore, I am using:
    omnetpp 5.4.1
    on Ubuntu 18.04
    and my last git pull refers to this commit ea4a8ae264c69c399b7fc713cc10b61ab03fb15f

**Comment by levy** [comment]
The upcoming INET 4.2 version will replace the old dimensional representation of the signal analog model inherited from MiXiM with a completely rewritten more flexible and more efficient version. The new code is already present in the master branch. You can try it now if you want to. The old code is not maintained anymore, there were some issues with it. The NED interface is pretty much the same. I close this issue, because it becomes obsolete with the new version. Thanks for reporting anyway!

[Presentation from the 2019 Summit](https://summit.omnetpp.org/2019/assets/pdf/math.pdf)
