### ISSUE TITLE
MultiFieldClassifier is not working

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#424]
There is a regression between INET 3.6 and 4.0 where the MultiFieldClassifier broke. It seems that the classifyPacket() method does not correctly extracts an Ipv4/Ipv6 header from the ethernet packet. The original code was using a recursively the getEncapsulatedPacket() call, to get the IP header, but the new code just checks for the protocol id of the actual packet (which is always EtherMac btw) and compares it to the ipv4/ipv6 protocol id (which obviously always fails) so the filter is never activated. (other modules in the diffserv package might be also affected).

**Comment by levy** [comment]
Yes, this is implemented incorrectly. If a header, which is not the first one, must be examined in a packet, then the PacketDissector class must be used, otherwise all sorts of misunderstandings can happen.

Furthermore, filtering for packets based on the data they contain, is directly supported by the new API by using the PacketFilter class. I guess this was left on the side of the road halfway through INET 4.0.

**Comment by ZoltanBojthe** [comment]
fixed on inet master
