### ISSUE TITLE
Sample-hold interpolation method with dimensional signal representation

### ISSUE THREAD

**Issue by ababila** [inet-framework/inet#436]
*For the sake of simple illustration of this issue, in what follows, we assume flat signals and power values are over time domain only (we omit the frequency domain).*

Assume two radio transmissions on the RadioMedium:

- Tr1 which starts and ends in [10,20] time interval with p1(=1w) as power value (let call this transmission blueTr).
- Tr2: which starts and ends in [20,30] time interval with p2(=2w) as power value (let call this transmission greenTr).

And assume a radio device is interested in what is happing on medium in the [10, 30] simtime interval (for example for a CCA or a reception of a transmission). Since the two signals overlap at 20 simtime, the power to be reported (according to my understanding of the framework) = the max power = the power at 20simtime = p1+p2 (=3w).
That is what one would get with scalar signal representation or dimensional signal representation with the linear interpolation method.

**The problem** is about dimensional signal representation when **sample-hold interpolation method** (the default configuration) is used.

With simple-hold parameter, `DimensionalTransmitterBase::createPowerMapping` will create these signals:

- blueTr:
------+-------------------------------------------------------------
Time  | 10.0000000000000000 29.9999999999989981 30.0000000000000000
------+-------------------------------------------------------------
power |  1.0000000000000000  1.0000000000000000  0.0000000000000000
------+-------------------------------------------------------------

- greenTr:
------+-------------------------------------------------------------
Time  | 20.0000000000000000 29.9999999999989981 30.0000000000000000
------+-------------------------------------------------------------
Power |  2.0000000000000000  2.0000000000000000  0.0000000000000000
------+-------------------------------------------------------------

Indeed, for implementing the sample-hold interpolation method in this context, setting the power value to 0 at the upper bound of a signal is the right decision. Otherwise, the value will be logically projected to infinity.

Thus, as illustrated in figure (I) below, the power value is undefined between the blue and green signal. (Q1) So, in such scenario: can it exist a maximum power in the [10, 30] time interval? (as it exists in the other models).
*Report max power as 2w would be wrong (0w from blueTr + 2w from greenTr at 20 simtime).*

![i2](https://user-images.githubusercontent.com/36278932/56817626-35230e00-6846-11e9-9532-4378085793e3.png)

Anyway, `MappingUtils.h::applyElementWiseOperator`, the function which contributes to respond to Q1 from the perspective of the current implementation enters an **endless loop**. 

Furthermore, not quite sure yet, but such scenarios may explain finally this bug https://github.com/inet-framework/inet/issues/422. Similar issues of `applyElementWiseOperator` function are occurring form the mentioned events. 

@adamgeorge309 @levy @avarga

**Comment by levy** [comment]
Thanks for reporting this issue. Entering an endless loop in `applyElementWiseOperator` is clearly a bug, no matter what the dimensional power mappings are. This code is inherited from MiXiM, so I'm not entirely familiar with it, and I guess it will take time to figure this out. Nevertheless, I think your analysis of the power mappings are not completely right. Let me clarify why.

In linear interpolation, at t=20 the line clearly cannot be vertical (even though it looks like in the figure), because you can't have two different values at the same time coordinate. So, if p = p1 at t = 10, and p = p1 at t = 20 (horizontal line), then it must be true that p != p2 at t = 20, but it also must be true that p = p1 at t < 20 and p = p2 at t > 20 (second horizontal line).

In step interpolation, the undefined power value actually doesn't exist, because there's no coordinate to access it. The coordinates are chosen, in both time and frequency domains, so that there's no representable coordinates between the p = p1 and p = p2 time coordinates. This is achieved by using the raw value of the time coordinates, and subtracting 1 (the smallest representable value). For the frequency coordinates, the implementation uses the `nexttoward` function to increment or decrement (a double) with the smallest representable value.

Please also note that the MAX value of p over the t = [10, 30] interval never being (p1 + p2) doesn't really matter, because in a real world system it wouldn't affect reception at all.

**Comment by ababila** [comment]
Copy that, thank you too for your clarifications.

**Comment by levy** [comment]
The upcoming INET 4.2 version will replace the old dimensional representation of the signal analog model inherited from MiXiM with a completely rewritten more flexible and more efficient version. The new code is already present in the master branch. You can try it now if you want to. The old code is not maintained anymore, there were some issues with it. The NED interface is pretty much the same. I close this issue, because it becomes obsolete with the new version. Thanks for reporting anyway!

[Presentation from the 2019 Summit](https://summit.omnetpp.org/2019/assets/pdf/math.pdf)
