### ISSUE TITLE
Printing power values of a dimensional signal (the output should be interpreted as dBW not dBm)

### ISSUE THREAD

**Issue by ababila** [inet-framework/inet#437]
For example, user express background noise power in dBm unit (in `IsotropicDimensionalBackgroundNoise`) but they should interpret the output (of `MappingBase.h::print` of the underlying power representation) as dBW, at the first appearance it's a bit embarrassing (a gap of -30).

**Comment by levy** [comment]
The upcoming INET 4.2 version will replace the old dimensional representation of the signal analog model inherited from MiXiM with a completely rewritten more flexible and more efficient version. The new code is already present in the master branch. You can try it now if you want to. The old code is not maintained anymore, there were some issues with it. The NED interface is pretty much the same. I close this issue, because it becomes obsolete with the new version. Thanks for reporting anyway!

[Presentation from the 2019 Summit](https://summit.omnetpp.org/2019/assets/pdf/math.pdf)
