### ISSUE TITLE
Ieee802154NarrowbandDimensionalRadio does not work if the radio medium uses linear interpolation

### ISSUE THREAD

**Issue by dstolpmann** [inet-framework/inet#439]
Hi,
I am trying to simulate communication between two sensor nodes using the Ieee802154NarrowbandDimensionalRadio. I have found out that the communication does work only if the analog model of the radio medium uses the "sample-hold" interpolation mode. If I change the interpolation mode to "linear", the communication does not work.

I have uploaded a minimal example that showcases this behavior at:
https://gist.github.com/dstolpmann/475af59b3937a8c309eb948e057bac9b

I am using OMNet++ 5.4.1 and INET 4.1 with #438 applied.

Best regards,
dstolpmann

**Comment by levy** [comment]
The upcoming INET 4.2 version will replace the old dimensional representation of the signal analog model inherited from MiXiM with a completely rewritten more flexible and more efficient version. The new code is already present in the master branch. You can try it now if you want to. The old code is not maintained anymore, there were some issues with it. The NED interface is pretty much the same. I close this issue, because it becomes obsolete with the new version. Thanks for reporting anyway!

[Presentation from the 2019 Summit](https://summit.omnetpp.org/2019/assets/pdf/math.pdf)
