### ISSUE TITLE
How to extend a App?  (e.g. UdpBasicApp)

### ISSUE THREAD

**Issue by LLipter** [inet-framework/inet#455]
I'd like to create a customized app. From my understanding, I should create a subclass of some existing app class(e.g. UdpBasicApp). However, when I try to create such subclass, I got an error.

![](https://i.ibb.co/3BRhB3g/Screen-Shot-2019-09-02-at-14-49-29.png)

(I've already added INET reference in project properties.)

**Comment by LLipter** [comment]
Are there any tutorials that can help me understand how to extend an existing class?

**Comment by rhornig** [comment]
Indeed, this is a bug in the above dialog in CDT. The dialog tests for the existence of the header file of the base class, but it was not prepared to look in all dependent projects. It can pull in only from the current project (which is sad, because on the other hand it can lookup the base class type info just fine from the index). Long story short, you should create your classes manually by creating the empty .h and .cc files.
