### ISSUE TITLE
Is 'procDelay' in Ipv4 (and other network layer modues) still relevant?

### ISSUE THREAD

**Issue by screw** [inet-framework/inet#512]
Is procDelay still relevant? Or was it dropped when moving from the QueueBase?

https://github.com/inet-framework/inet/blob/b8e40e38611ba53fa2cc79b5f85b3684c8d73eaa/src/inet/networklayer/ipv4/Ipv4.ned#L99

**Comment by levy** [comment]
No, it's not used and it should be removed. Modelling processing delay that way was wrong.

**Comment by screw** [comment]
Is there another way how to simulate processing delay?

**Comment by levy** [comment]
You can always add a delayer module before the Ipv4 module. I'm not sure if this correctly models what you want.

**Comment by screw** [comment]
I guess it doesn't. Because normally when a node processes one packet the others wait (are delayed), but with the PacketDelayer packets can overtake each other when the delay parameter is a distribution.
Anyhow, I wanted to try it out, but when I connect the packetDelayer under tcp module like:

```
        tcp.ipOut --> tcp_delayer.in if hasTcp;
        tcp_delayer.out --> tn.in++ if hasTcp;
        tcp.ipIn <--  tn.out++ if hasTcp;
```

I get an exception because PacketDelayer can handle only selfMessages

```
void PacketDelayer::handleMessage(cMessage *message)
{
    if (message->isSelfMessage()) {
        auto packet = check_and_cast<Packet *>(message);
        pushOrSendPacket(packet, outputGate, consumer);
    }
    else
        throw cRuntimeError("Unknown message");
}
```
The above code indicates that I am not using it correctly but I can't figure out a way how to connect it to the layers in standard host/router without the need to change code in ipv4/tcp/ etc.

**Comment by levy** [comment]
Oh, I'm sorry but I didn't necessarily mean the PacketDelayer module but some kind of delay mechanism. If you need to keep the order of packets while using random per-packet delay then PacketDelayer is the wrong choice because it simply uses the FES to store the packets.

Hmm, apart from that, you are right that PacketDelayer in its current implementation doesn't support working as a standalone module. This is clearly wrong and should be fixed. 

To solve your problem, you could put a PacketQueue connected to a PacketServer, similarly to the ones in LeakyBucket, or just simply use this compound module. The intent is that you should be able to solve this problem without changing the code in IPv4 just by simply deriving a module from Ipv4NetworkLayer, adding a new submodule for the delaying mechanism and reconnecting the connections.

I hope this helps.

**Comment by levy** [comment]
This has been fixed at least to the extent that a PacketDelayer module can be put in front of the Ipv4 module in the Ipv4NetworkLayer compound module and it works as expected.
