### ISSUE TITLE
Compilation fails on Ubuntu 18

### ISSUE THREAD

**Issue by keithbriggs** [inet-framework/inet#540]
I have a standard Ubuntu 18 installation, fulling up-to-date.  I get:

inet/environment/ground/OsgEarthGround.cc
In file included from inet/environment/ground/OsgEarthGround.cc:25:0:
./inet/visualizer/scene/SceneOsgEarthVisualizer.h:51:18: error: ‘virtual void inet::visualizer::SceneOsgEarthVisualizer::initializeScene()’ marked ‘override’, but does not override
     virtual void initializeScene() override;
                  ^~~~~~~~~~~~~~~
Makefile:1754: recipe for target '../out/gcc-release/src/inet/environment/ground/OsgEarthGround.o' failed
make[1]: *** [../out/gcc-release/src/inet/environment/ground/OsgEarthGround.o] Error 1
make[1]: Leaving directory '/home/kbriggs/Downloads/inet4/src'
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by torokati44** [comment]
More than 2 years has passed since the reporting of this bug, so closing as assumed stale. Apologies for not getting a response in the meantime.
By the way, if OSG and/or osgEarth are causing build problems, and are not necessary for the project at hand; usage of both can be disabled as OMNeT++ configuration options, and as INET features.
