### ISSUE TITLE
Negative Queue Length due to Statistic Recording and Warmup Period

### ISSUE THREAD

**Issue by Buddahbrot1** [inet-framework/inet#549]
Hi,
we are currently looking into the functionality of DCF AP mode in IEEE 802.11. 
After some quick test and analysis we found strange vector results for the queue size of the DCF pending queue.
The detailed statistic in question can be found under:
`*.ap.wlan[0].mac.dcf.channelAccess.pendingQueue::queueLength	`
where `ap` is a simple AccessPoint.

In our simulation results, the queue length showed negative values which obviously cannot happen in reality.
We found that the statistic in question is computed by considering four basic statistics, namely:
`        @statistic[queueLength](title="queue length"; type=int; source=count(packetPushed) - count(packetPopped) - count(packetRemoved) - count(packetDropped); record=max,timeavg,vector; interpolationmode=sample-hold);
`
[packetQueue.ned](https://doc.omnetpp.org/inet/api-current/neddoc/src-inet-queueing-queue-PacketQueue.ned.html)

This definition of the queue length statistic should work fine if one considers the logic behind it, however, the behavior between any warmup period consideration and the statistic collection behaviour introduces a problem.

Since no statistics are collected during the warmup period, the count() functions for the queue length statistics are also not called.
However, the queue can and will fill up during this period and can be partially filled at the moment the warmup period ends.
Only after the warmup period, the count() functions are called correctly and the number of packets put into the queue is tracked.
Unfortunately,  packets can and will be popped as well, allowing for the queue length to go to negative values.

The bug can be somewhat summarized by:
The queue length range is shifted downwards by the fill level of the queue at the moment in time the warmup period ends.

![image](https://user-images.githubusercontent.com/44811861/87417269-2ef68a00-c5d0-11ea-9831-33a4da6ae7d0.png)

As you can see in this graph the warmup period of 30 seconds causes a downward shift of the queue length size by roughly 60 packets.

Right now, we do not see a clean and simple fix to this bug.
One possibility would be to relocate the statistic calculating into the packet queue source file, but this would only fix the problem for this specific module and leave other modules with similar statistic calculation bugged.

We appreciate every advice regarding this fundamental statistic collection problem.

**Comment by avarga** [comment]
We seem to have figured out a solution, but it will require a (slight) modification in the OMNeT++ source.

Warmup period is implemented with a special result filter (class WarmupPeriodFilter), which basically swallows everying until the configured warmup period is over. This warmup filter is inserted automatically into the filter chain (actually DAG), right at the input signals. This causes the problem in the case you described. 

If, instead, the warmup filter was inserted at the end (so it would not affect the computation, only the recording), it would be perfect. Unfortunately that is not currently possible.

The idea is that we add an option to @ statistic to turn off automatic adding of the warmup filter. Then one could manually add a warmup filter to whichever place in the expression it is appropriate.

To clarify, currently the filter chain generated automatically for the statistic is something like this:

`@statistic[queueLength](title="queue length"; type=int; source=count(warmup(packetPushed)) - count(warmup(packetPopped)) - count(warmup(packetRemoved)) - count(warmup(packetDropped)); record=max,timeavg,vector; interpolationmode=sample-hold);`

when we would actually need this:

`@statistic[queueLength](title="queue length"; type=int; source=warmup(count(packetPushed) - count(packetPopped) - count(packetRemoved) - count(packetDropped)); record=max,timeavg,vector; interpolationmode=sample-hold);`

but that's not possible currently, because the warmup filter is automatically added, unconditionally. We plan to add a @ statistic option to disable that.


@statistic[queueLength](title="queue length"; type=int; source=count(packetPushed) - count(packetPopped) - count(packetRemoved) - count(packetDropped); record=max,timeavg,vector; interpolationmode=sample-hold);

**Comment by Buddahbrot1** [comment]
Thanks for the swift response and the throughout answer.

Adding an additional option to disable the `warmup` wrapping is definitely a good feature to have and would solve the problem at hand! :+1:

Out of curiosity: Is there a reasons to wrap each element of the `source` input with a `warmup` filter individually, instead of defaulting to a single wrap around the entire source input like you described in your second code snippet?

**Comment by avarga** [comment]
We have considered simply moving the warmup filter to the end of the computation, but that would mess up other statistics that are correct now. For example, if you write `min(foo)`, do you really mean `min(warmup(foo))` or `warmup(min(foo))`? 
The first one completely ignores the values emitted during the warmup period, the second one includes them but only starts recording after the warmup period. Either option may make sense, it really depends on what you want? What is the purpose statistics?

**Comment by Buddahbrot1** [comment]
Thanks for taking the time and giving the insight.
You are right that `min()` is a good counter example against that approach.

**Comment by avarga** [comment]
`
diff --git a/src/sim/cstatisticbuilder.cc b/src/sim/cstatisticbuilder.cc
index 007f97a4eb..3bddc0b30f 100644
--- a/src/sim/cstatisticbuilder.cc
+++ b/src/sim/cstatisticbuilder.cc
@@ -120,7 +121,9 @@ void cStatisticBuilder::doAddResultRecorders(cComponent *component, std::string&
         if (signal == SIMSIGNAL_NULL) {
             const char *sourceSpec = opp_emptytodefault(statisticProperty->getValue(PROPKEY_STATISTIC_SOURCE, 0), statisticName);
             bool hasWarmupPeriod = getSimulation()->getWarmupPeriod() != SIMTIME_ZERO;
-            source = doStatisticSource(component, statisticProperty, statisticName, sourceSpec, checkSignalDecl, hasWarmupPeriod);
+            TristateBool warmupAttr = parseTristateBool(statisticProperty->getValue("autoWarmupFilter"), "warmup attribute");
+            bool needWarmupFilter = hasWarmupPeriod && warmupAttr != TRISTATE_FALSE;
+            source = doStatisticSource(component, statisticProperty, statisticName, sourceSpec, checkSignalDecl, needWarmupFilter);
         }
         else {
             source = SignalSource(component, signal);
`

**Comment by avarga** [comment]
See patch above. Apply this to OMNeT++, and in INET, change the statistic to this:

`@statistic[queueLength](title="queue length"; type=int; source=warmup(count(packetPushed) - count(packetPopped) - count(packetRemoved) - count(packetDropped)); record=max,timeavg,vector; interpolationmode=sample-hold; autoWarmupFilter=false);`

That is, add the `autoWarmupFilter=false` attribute, and wrap the expression into `warmup()`.

Patch will be part of OMNeT++ 6.0 and next 5.6 patch version.

**Comment by avarga** [comment]
Leaving it open until we fix it in the INET repo too.

**Comment by levy** [comment]
Fixed several other cases in INET master.
