### ISSUE TITLE
INET (queueing) modules ignore channel definition (cChannel class)

### ISSUE THREAD

**Issue by Kathess** [inet-framework/inet#553]
**Platform**
 - OMNeT++ version: 5.6.1
 - INET version: 4.2.0
 - OS: Linux Mint 19.3 

**Describe the bug**
When using INET modules, the channel definition is completely ignored. Regardless, of the channel-type (tested with DatarateChannel, DelayChannel and own delay definition, see example code). One would expect that a packet would get delayed or get lost (e.g. if the channel parameter "disabled" is set to true) but the channel definition is just ignored. No error, no warning, just no effect.

**To Reproduce**
I've appended a minimalistic example project, just including one .ini and one .ned file. Even though, a delay is configured in the NED file, the delay that the packet experienced at the sink will always be 0. To run it, the reference to the current INET version needs to be set and to observe the delay, the sink's code could be extended with the following line in the function `void PassivePacketSink::consumePacket(Packet *packet)`:

```C++
simtime_t creationTime = packet->getCreationTime();
EV << "Packet delay: " << simTime() - creationTime << endl;
```

Here is the critical code, which is also included in the ZIP file:
```ruby 
    submodules:
        producer: ActivePacketSource {
            @display("p=100,100");
        }
        consumer: PassivePacketSink {
            @display("p=300,100");
        }
    connections:
        producer.out --> {  delay = 100s; } --> consumer.in; 
```

[channelBug.zip](https://github.com/omnetpp/omnetpp/files/5031373/channelBug.zip)

**Comment by levy** [comment]
Thanks for moving the issue here!

Well, I'm not sure if this is a bug or a feature request, because the synchronous API between queueing model elements was never designed to work with channels. Nevertheless, I think this could work the following way.

When a packet is being pushed from one module to another, then if the channel is not an ideal channel, the packet would be sent instead of being passed via pushPacket. This would only be done if the receiving module actually supports sending packets on the input gate.

As for pulling packets, I think there's no right solution, because it's a synchronous operation and there's no way to pull a packet asynchronously. So if a module wants to pull a packet from another and the channel between them is not an ideal channel, then an error is to be signaled.

This gets even more complicated when packet streaming is used with the synchronous API. This is a new feature that will be added in the INET 4.3 version.

I'm not quite sure if this solution worth the hassle. So I'm open to about it.

**Comment by Kathess** [comment]
This is very informative, thank you very much.

I've currently worked around this problem by implementing a "Channel Module" which simulates link behavior.
It includes (among others) a server module (PacketServer) for the transmission delay (max. packet capacity one) and a delay module (PacketDelayer) for the propagation delay. It also has a queue which could be set to capacity zero to simulate a disabled link.

This of course requires an extra module for every link but it might be okay, regarding the effort that would be needed to change the INET packet passing behavior.

**Comment by levy** [comment]
Hmm, that's a completely valid way to model channels like that. In fact, we always had in the back of our mind the idea of channels as modules, but never actually thought that it could be already implemented this way, using the INET queueing model elements.

BTW, the upcoming INET 4.3 will introduce a whole bunch of new generic protocol support components (aggregation, fragmentation, crc/fcs, acknowledgement, transmitter/receiver, etc.) using the very same synchronous packet processing API that is implemented by the queueing model elements.

**Comment by Kathess** [comment]
Really looking forward to it!
Thanks for the nice response and the great work!
