### ISSUE TITLE
Discrimination header protocols

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#578]
The actual wireless mac protocols don't check if the header is correct if you have two nodes with different protocols the simulation will abort.
A possible solution could be this
https://github.com/aarizaq/inetmanet-4.x/commit/315998b35e8a7dec7116f8e57307da41c4eaa80f

**Comment by levy** [comment]
Hmm, dynamic casting is not a proper solution, because it won't work if the packet uses a binary chunk for representation.

The underlying problem is that (even though the APSK radio does have a MAC protocol field) the network interface is set up in a way that the PHY unconditionally sends the correctly received frame up to the MAC, and then the MAC does not check for the right packet protocol. The best solution would probably be to add a field to the APSK radio to filter for a specific MAC protocol.

**Comment by aarizaq** [comment]
The radio transceiver should send to the upper layer any message correctly received.
Probably, the easier solution is to include a tag in the mac layer (sendDown can include a wirelessProtcolTag or something similar) and the receiver can check the tag, remove it or delete the packet if the tag is incorrect.

**Comment by levy** [comment]
I disagree with the packet tag solution and here is my reasoning.

Packet tags intentionally don't go through the wireless transmission medium. The only data that is available for the receiver is the "bytes" in the packet (even if it's in the form of field based chunks). Since the two receivers in this case use the same PHY technology (ApskRadio), they will inevitably receive each others' frames successfully. On the other hand, in the two MAC protocols, it would be really weird to receive a packet with a completely unrelated MAC protocol just to discard it. So I see no other solution than to filter the packets based on the MAC protocol in the PHY. BTW, the ApskPhyHeader already contains a protocol field, because this hypothetical PHY was assumed to be used by multiple MAC protocols from the beginning. This is not the case in most wireless technologies. Alternatively, we could put another component between the PHY and the MAC that filters for the supported protocol.

**Comment by aarizaq** [comment]
Ok, if the tag cannot go, and the header casting is not a good solution, the only alternative is to include this information in the physical layer header.
Without loss of generality, the mac layer can be registered in the physical layer the protocol type using a primitive in the initialize phase, and the radio can include the type automatically and filter any packet that the protocol is not correct.
The reason to discriminate in the mac was due to my experience with microcontrollers, sometimes you use basic transceivers, and it is the mac that must filter the packets.

**Comment by aarizaq** [comment]
Other possible solution
https://github.com/aarizaq/inetmanet-4.x/commit/d35982f1b1e5e3e062a98be138cd5b95f142a306

The objective of this solution is to modify the minimum number of files.
It is possible that is not the most elegant and probably, different that you have in mind.

**Comment by levy** [comment]
I would prefer something like this: #c3c7ad4f58e9258611d4ea1559e283395e3b47b0
Please note that this has not been tested.

**Comment by aarizaq** [comment]
Umm, Shouldn't this be implemented in a more basic class to affect all the radio models?

There is plan to use ApskRadio like the base radio model?

**Comment by levy** [comment]
No, there's no such plan and the real radio models (like IEEE 802.11) don't have a protocol identification field in their PHY headers.

**Comment by aarizaq** [comment]
If the other radio modules don't have problems to discriminate the frames, is enough

**Comment by levy** [comment]
I pushed a somewhat updated version of the above patch to master. The protocol parameter of ApskRadio is optional, if not specified then all packets are passed up. If the parameter is specified, then ApskRadio expects packets of the given protocol from the upper layer and only passes up packets received with the given protocol in the PHY header.
