### ISSUE TITLE
Incorrectly added multi-dimensional (time x frequency) analog signal representations (inherited from MiXiM)

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#62]
The original Mac80211::createSignal implementation in MiXiM returns a two-dimensional (time x frequency) analog signal representation. The transmission power is constant over the provided range of time and frequency. Nevertheless, the signal uses linear interpolation between its defined points. It also uses the so called out of range value that is set to 0.

These signals are summed up when the RSSI and the SNIR is calculated. The result is also represented using linear interpolation and the out of range value. Unfortunately it's impossible to correctly represent the result this way, because the original signals have more discontinuity (at different locations) in total than the result can represent. In fact the result will interpolate at certain ranges where it should have a discontinuity instead.
Additional Information  The attached figure shows two signals before they get added, the expected result, and the actual result. Adding further signals to them makes it even worse...

The following code demonstrates the error in the original MiXiM 1.0 version. To compile the code, the Mac80211::createSignal function must be public. The error still exists in the latest MiXiM 2.3 version. This code should print 101, but it prints 107.667, which is wrong.

Mac80211 mac;
ConstMapping _m1 = mac.createSignal(2, 4, 1, 2E+6)->getTransmissionPower();
ConstMapping *m2 = mac.createSignal(1, 2, 10, 2E+6)->getTransmissionPower();
ConstMapping *m3 = mac.createSignal(4, 1, 100, 2E+6)->getTransmissionPower();
ConstMapping *mTotal = MappingUtils::add(_MappingUtils::add(_m1, *m2), *m3);
std::cout << MappingUtils::findMax(_mTotal) << endl;

The consequences of this bug to higher layer statistical results is unknown.
![image](https://cloud.githubusercontent.com/assets/40529/6642462/176d4838-c9a5-11e4-949e-af7d82036161.png)

**Comment by levy** [comment]
The upcoming INET 4.2 version will replace the old dimensional representation of the signal analog model inherited from MiXiM with a completely rewritten more flexible and more efficient version. The new code is already present in the master branch. You can try it now if you want to. The old code is not maintained anymore, there were some issues with it. The NED interface is pretty much the same. I close this issue, because it becomes obsolete with the new version. Thanks for reporting anyway!

[Presentation from the 2019 Summit](https://summit.omnetpp.org/2019/assets/pdf/math.pdf)
