### ISSUE TITLE
Question about one library EtherEncap.h

### ISSUE THREAD

**Issue by NikolaosGian** [inet-framework/inet#769]
Hello everyone,
I just install new version of OMNeT++6.0 but the library with name EtherEncap.h dosen't exist.
Before i was using OMNeT++5.0 with iNET-3.2.4 and now i using iNET: 4.3.9(stable).
Someone know where the library get included to other file ?

**Comment by rhornig** [comment]
Ethernet model was (several times) rewritten since INET 3.2 so the code is organized differently and you will not find a header file with exactly the same functionality. Look at `src/inet/linklayer/ethernet/basic/EthernetEncapsulation.*` which might do something similar. Note that there are actually two ethernet models in INET: One very basic (that contains the above code) andthere is a more complex modular implementation with a lot more features.

**Comment by NikolaosGian** [comment]
Greate thanks you @rhornig i have an another question. 
I need to find the EtherFrame.h but dosen't exist at new version we know where have been included?
