### ISSUE TITLE
InterfaceRelayLayer does not support disabeling MAC learning

### ISSUE THREAD

**Issue by Musteblume** [inet-framework/inet#807]
Hi,

it would be nice if the InterfaceRelayLayer would have a parameter to set that would replace the RelayInterfaceLearner with simple forwarding. This way a network could have static forwarding tables.

Best regards
Philipp

**Comment by levy** [comment]
You can omit the learner submodule by simply setting the typename to an empty string:

**.interfaceRelay.learner.typename = ""

This setting tells omnet to use the OmittedPacketFlow module instead of the default RelayInterfaceLearner module. The OmittedPacketFlow module removes itself from the module hierarchy during initialize. It also makes sure that the external connections in its parent follow its own internal connections. This is basically a simply way to specify how to omit an optional submodule.

See the learner submodule declaration in the InterfaceRelayLayer module, it uses the IPacketFlow module interface, also see the @omittedTypename(OmittedPacketFlow) declaration on the IPacketFlow module interface.

**Comment by Musteblume** [comment]
Thank you! That is a nice concept which i wasn't aware of.
