### ISSUE TITLE
Unexpected Strict priority shaper behaviour

### ISSUE THREAD

**Issue by mchekhovoi-tsn** [inet-framework/inet#827]
**Brief**
Unexpected Strict priority shaper behaviour.

**Environment, preconditions**
Windows 10, OMNeT++ 6.0.1, inet 4.4.

**Simulation description**
We are simulating the Strict Priority Shaper behavior as part of our evaluation of the Omnet Tool for TSN.
We simulate a network with two talkers/clients, one switch and one listener/server.
See network topology on the screenshot below.

**Test strategy**
Simulate the behavior of the strict priority shaper by adding packets to separate queues of a switch port,
and using the gates in the closed position to hold all the packets in the queues.
Once all packets are in the queues we then open the gates at exactly the same time and then monitor which packets are selected for transmission. 

**Steps to reproduce**
1. Compose the network with two talkers/clients, one switch and one listener/server. (See the content of ned and ini files below.)
2. Generate a single UDP packet from each client, with packetLength = 1000B.
To use only one packet from the client - set extremely large productionInterval = 15s.
3. Set different PCPs ("2" and "5") for the streams.
4. Set numTrafficClasses = 8 at the switch.
5. Set up a Time aware shaper at the switch, with the same offsets and durations for both used queues.

**Expected result**
Packet of stream with PCP = 5 is used for transmission just after gates are opened, since it has higher priority.

**Actual result**
Single packet from stream with PCP = 2 is used just after the gates are opened. See attached charts.

**Reproduce rate - always.**

[SimpleNetwork.ned.txt](https://github.com/inet-framework/inet/files/9918139/SimpleNetwork.ned.txt)
[omnetpp.ini,txt](https://github.com/inet-framework/inet/files/9918140/omnetpp.ini.txt)

**Network topology and charts with test results are below.**
![изображение](https://user-images.githubusercontent.com/117265548/199442186-427a539d-a62b-4fba-8c75-65c7759b6189.png)
![изображение](https://user-images.githubusercontent.com/117265548/199442295-92f0e92b-ce92-445c-8129-b49bf8d4c208.png)
![изображение](https://user-images.githubusercontent.com/117265548/199442327-3a90687a-b4bc-473f-8a76-1843e6546fee.png)
![изображение](https://user-images.githubusercontent.com/117265548/199442353-702c1115-4b9e-4ec0-accd-4e89efbb49e0.png)

**Charts from test with some parameters changed are below (modified values are added to screenshots as well)**
![изображение](https://user-images.githubusercontent.com/117265548/199442413-41dc0802-12ee-4d34-8d89-7f3aef8989eb.png)
![изображение](https://user-images.githubusercontent.com/117265548/199442428-2694fe95-914f-4409-afa8-7ace6c7ebfff.png)

**Comment by levy** [comment]
Without looking too deep into this issue, my guess is that opening the gates at the exact same time is the root of the problem. Probably the lower priority gate opens first and the packet is sent out immediately. Just because the events happen at the exact same time, there still is a definite order between them. The strict priority shaper doesn't wait until all events are processed at the same simulation time because there's no easy mechanism for that.

In general, this isn't a problem because in real life things never happen at the exact same time. Maybe in this case it's different because opening the gates can really be scheduled to the exact same time. The gate schedules are defined according to the local clock (or simulation time if there's no simulated clock) and they can have the exact same values.

**Comment by mchekhovoi-tsn** [comment]
`Probably the lower priority gate opens first and the packet is sent out immediately.`
Yes, that's true.

**Comment by levy** [comment]
As for now, a possible workaround may be to use a PacketServer with 0 processing time instead of the default InstantServer as the server submodule of the EthernetMacLayer compound module.

**Comment by ameer-tsn** [comment]
Hi @levy, some info on Qbv operation according to the IEEE standard and on real devices: A gate control entry holds the state of all gates, and the entry is executed immediately when it is configured to be executed within the cycle. This is to say that all gates are set to the states in the gate control entry at the same time - there are no states in between. And the transmission selection occurs after the gates are set.

The current behavior would cause an interfering fame case - which should not occur in this case. So a critical frame can be delayed by the max frame size of a lower-priority frame.     

Another thing to note is that the gate control entry can be one of many entries in a gate control list (GCL), do you plan to support the GCL?

![image](https://user-images.githubusercontent.com/117711762/200496752-cf72db20-003d-48f1-b7fe-1ab20862201d.png)

**Comment by levy** [comment]
There is a pull request #776 related to a module directly implementing GCL, but it isn't merged in yet. Even if this would be merged in, the gates also need to be changed somewhat not to notify the transmission selection about state changes. The reason is that gate states are changed one-by-one either from a sequence of events or a from for loop in the GCL module. Also, the GCL module would have to notify the transmission selection module to do its job once all gates are set.

Please note that these gate modules are quite generic and they can be combined in many other ways. Anyway, I think it makes perfect sense to come up with IEEE specific modules if that is required to properly implement the behavior.

My suggestion of using a 0 delay PacketServer should solve the interfering frame case, because it delays the frame selection in the server after all gates at the same simulation time are set.

**Comment by levy** [comment]
Another workaround could be setting the scheduling priority of the gate changeTimer message using a module parameter. This way the times would still be the same.

Another would be reversing how the traffic categories are mapped to the order of the transmissionGates.

Another would be to schedule a self message in the server before pulling the packet.

Unfortunately, none of these are really satisfying.

**Comment by levy** [comment]
The af0103767e62213de07d8944e9479cad6a31ad2e patch allows controlling the changeTimerSchedulingPriority of the gates.
The c4bc50745ff6a2dd5150e1abef4f74cde7c3c049 patch changes the default in the Ieee8021qTimeAwareShaper.
These changes should get rid of the small time differences in your workaround.

**Comment by mchekhovoi-tsn** [comment]
I tested two proposed patches with two and three streams with different PCPs - now works fine on standard PCP-to-queue mapping.

However just I noticed - if we use "reversive" mapping (for example, for three streams:)

**Comment by levy** [comment]
Thanks for testing.

Meanwhile I'm working on the final solution for this issue (and also on other issues) which will allow the user to also request a separate event in the server module with a parameter setting. The separate event will always happen after all gate events are completed (no matter in what order), so the end result will be correct.

**Comment by levy** [comment]
This should be fixed in the master branch. The fix adds an optional separate event in packet servers to start serving the packets with a user defined scheduling priority. By default, this feature isn't used, but the EthernetMacLayer enables this with
```serveSchedulingPriority = default(0);```. The serve event is always scheduled after all gate state change events, so the traffic class priority will be taken into account correctly by the strict scheduler by the time the packet server starts serving a packet.
