### ISSUE TITLE
[IEEE 802.1Qci PSFP] Packets are forwarded through closed Gates

### ISSUE THREAD

**Issue by EpplerM** [inet-framework/inet#830]
I failed to filter Packets with the Gates inside the (Simple-)Ieee8021qFilter. I used the Showcase tsn/streamfiltering/tokenbucket and closed the gates with the omnetpp.ini file but the packets were sent through the closed gates.
Is there an easy fix to implement that the Packet gets dropped?
[omnetpp.ini.txt](https://github.com/inet-framework/inet/files/9970769/omnetpp.ini.txt)

**Comment by levy** [comment]
Packets should not be sent through closed gates, it would clearly be a bug.
Please provide a convincing description of the problem with logs or charts or something and a reproducible test case.

**Comment by levy** [comment]
The bug is that the classifier doesn't check that the selected gate index can be pushed with the packet or not. In case the selected branch has back pressure then the default branch should be selected. If the default branch also has back pressure then an error should be raised.

**Comment by levy** [comment]
This should be fixed in the master branch. The order of submodules have been changed in the SimpleIeee8021qFilter so that the gates come first. Also the StreamClassifier has been modified to classify packets to the output gate only if the gate can be pushed. All packet gates signal an error if a packet is being pushed through while the gate is closed now.

There are three options per stream:
 - opening the gate and configuring the parameters of the meter/filter causes the stream to be limited to the specified datarate
 - closing the gate causes the stream to be forwarded through the default gate without filtering
 - setting the filter expression to the empty string causes the stream to be filtered out completely
