### ISSUE TITLE
Oscillator compensation factor is set incorrectly with gPTP

### ISSUE THREAD

**Issue by adamgeorge309** [inet-framework/inet#853]
At a time synchronization event, the compensated drift rate of slave clocks is calculated from the time of the master clock at the current sync event, and the previous sync event. 

On the clock time difference to simulation time chart, we should be able to get the compensated rate of the slave clock at the current sync event by
connecting the master clock's values at the previous and current sync event's time.

However, in some cases it doesn't work like it is supposed to. Here is an example:

![rateconpensationerror2](https://user-images.githubusercontent.com/17473608/215572905-274a3da6-d8df-4122-ad13-5fe548160243.png)

This can be observed when both the master and slave clock has random clock drift rate. For example: showcases/tsn/timesynchronization/gptp, Primary and hot standby master clocks, all clocks chart

**Comment by levy** [comment]
I've done some validation:
 - created a network of two nodes: master and slave
 - set the link delay to 0s
 - disabled pdelay measurement to eliminate link delay from the synchronization
 - changed SettableClock to emit clock time 10 times as often as the RandomDriftOscillator changes its drift
 - set inititalDriftRate to uniform(-1000000ppm, 1000000ppm) to make it large enough, so it's easy to see if there's any error
 - set driftRateChange to 0ppm and also to uniform(-1000ppm, 1000ppm) to see how the synchronization deals with the no change and small change cases
 - set master clock to be perfectly follow the simulation time (i.e. no drift)

Observation:
 - if the slave clock drift rate doesn't change then gPTP eliminates the clock speed difference on the first complete synchronization at the 2nd synchronization event because the slave clock drift estimation requires two synchronization events
 - if the drift rate changes every 10ms with uniform(-1000ppm, 1000ppm) then the following chart shows the slave clock synchronization events

![image](https://user-images.githubusercontent.com/112461/216267179-457f7741-832e-4313-9310-cded1dccc133.png)

The blue lines show the estimated and the actual clock drift of the slave clock, and also the remaining clock drift at each synchronization event. Ideally the remaining clock drift should be zero after the oscillator clock drift compensation is applied at the synchronization event, but due to the inaccurate measurement of the actual clock drift, some clock drift remains. The chart shows that what remains is consistent with the difference between the actual and the measured clock drift at each synchronization event. This is expected because the clock drift that cannot be measured cannot be eliminated. So this validation gives us some proof that the gPTP synchronization code works as expected.
