### ISSUE TITLE
GPS simple module for extracting node location

### ISSUE THREAD

**Issue by n-jay** [inet-framework/inet#865]
I'm currently reverse-engineering a routing protocol that requires "node position" data for clustering purposes. Nodes in this situation are static although placed randomly.
While extracting it via `getCurrentPosition()` is possible, the authors suggest using a GPS module for this purpose.
Since using a GPS module will also incur a battery drain I was hoping there was a GPS module INET that would satisfy this purpose.

If not, I'm hoping to develop one and contribute to INET.

**Comment by levy** [comment]
There's no GPS module in INET, and I don't know what would be your goal by implementing one. Getting the current position of a network node is pretty straightforward already using the mobility submodule.

I don't know what should I do with this issue, because it isn't a bug and it isn't really a feature extension of INET either. Developing new modules on top of INET are not meant to be added to the issue tracker.
