### ISSUE TITLE
Real-time scheduler class conflicts with aodv network？

### ISSUE THREAD

**Issue by zhangteng0526** [inet-framework/inet#878]
Because there is a router in my aodv network that contains an ExtLowerEthernetInterface, I need to set the scheduler-class=" inet:: RealTimeScheduler "in the ini file.". However, after this, the aodv node does not transfer the received RREQ message upward.  Therefore, the entire aodv network was destroyed.  "Is there any way to do this? I'm puzzled now. Thank you very much for your help

**Comment by levy** [comment]
This is an issue tracker of the INET framework. Please use the mailing list to ask questions.

**Comment by zhangteng0526** [comment]
I think this is a problem with INET, as aodv is under the INET framework, while the RealTimeScheduler scheduling class is also under the INET framework. If I want to inquire about these issues, what should I do? I have sent you an email before, but unfortunately I did not receive a response from you

**Comment by levy** [comment]
If you want to report an issue, then please be more helpful, because you are asking others to spend *their* time on *your* problem. Try to narrow down the problem to a minimal simulation, attach the necessary NED/INI files, state what is expected and what happens instead, give the exact steps to reproduce the issue, etc. So far we only have a vague description of something that may or may not be an issue. Nobody is going to spend time on figuring out whether it really is an issue or just some misconfiguration.
