### ISSUE TITLE
GSPR not working properly

### ISSUE THREAD

**Issue by maicuongtho** [inet-framework/inet#938]
It seems like the GSPR protocol is not installed correctly.
![GPSRerror](https://github.com/inet-framework/inet/assets/17454951/702dd7b1-138c-4ab1-a259-c00e08336288)

With the sending node being U2, the destination node being U10. At node U3, the packet should be forwarded to node U5, but instead it is forwarded to U11

**Comment by avarga** [comment]
Can you attach the simulation setup (NED and ini files)? We need it for reproducing the issue, which is a prerequisite to fixing it. Also, which INET version are you using?

**Comment by maicuongtho** [comment]
[gpsr-uf.zip](https://github.com/inet-framework/inet/files/13777827/gpsr-uf.zip)
i use INET4. I include .ned and .ini files in the compressed file because git does not allow these types of files to be attached

**Comment by levy** [comment]
It's not necessarily a bug. GPSR has two modes of operation: greedy routing and perimeter routing. The routing started at U2 in greedy mode but failed to reach U10 because it had to turn around at U7. Arriving back to U2, GPSR switched to perimeter routing to go around the "obstacle". In this mode it might be perfectly valid to choose U11 at U3 as the next hop. I think perimeter routing mode is exited at U5 when the packet is closer to the destination than it was ever before.

**Comment by levy** [comment]
I think the explanation above clears this issue.
